on:
    workflow_dispatch:
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run My Custom Action
              uses: ./
              with:
                  prettier-version: "2.7.1"
